### PR TITLE
Update libpl

### PR DESCRIPTION
**Pull request by mpharoah**
Upstream changes:
https://gitlab.com/parallel-launcher/libpl/-/compare/d6b3a90d096183df54d2c69a4d64e0ced8dda811...cfc74e5898945699bb1f5aeee8dd5507164e2384?from_project_id=48179234&straight=false

### CODE REVIEW

**Review by gheskett — APPROVED** [review]

**Review by gheskett — APPROVED** [review]

**Comment by gheskett** [comment]
(And this is why I don't merge stuff instantly)

**Comment by mpharoah** [comment]
Actually, going to make one more change. It should _require_ Parallel Launcher 7.1.0 for LPL_ABI_VERSION_5 to be supported-- only the core itself needs to be up to date

**Review by gheskett — APPROVED** [review]
wow no way such libpl content

**Comment by mpharoah** [comment]
Okay, it's good for real now

**Comment by mpharoah** [comment]
Verified with a test rom based off this branch
image

**Comment by gheskett** [comment]
Alright fine I'll bite

**Pull request merged**
