### PR TITLE
Save up to 130KB of RAM at literally zero cost

### PR DESCRIPTION
**Pull request by arthurtilly**
Lol

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
Huh.

**Comment by gheskett** [comment]
Actually wait, I'm not 100% convinced this is safe. What happens if your cell doesn't have any surfaces in it? Normally this would mean that your next entry is null, but is it actually possible for the head pointer to be null in this case?

**Comment by arthurtilly** [comment]
why would it not be possible for the head pointer to be null. (*cells)[SPATIAL_PARTITION_FLOORS] = NULL;

**Comment by gheskett** [comment]
Okay I looked at it a bit more and I don't actually see anywhere where the surface partition lists are even being written to to begin with (apart from the NULL cases). Did you actually test this?

**Comment by arthurtilly** [comment]
?? ofc i tested it it works fine lol, theyre written in the same places they usually are

**Comment by gheskett** [comment]
Maybe I'm just blind but I don't see how those pointers could be set to any value other than NULL

**Review by gheskett — CHANGES_REQUESTED** [review]
Yeah this is definitely missing something

**Review by gheskett — APPROVED** [review]
Okay this seems better I think idk pointer logic like this is sorta hard to read and validate

**Pull request merged**
