### PR TITLE
Merge 2.1.0 into lighting engine

### PR DESCRIPTION
**Pull request by Reonu**
hi wiseguy

### CODE REVIEW

**Comment by Reonu** [comment]
I have decided to merge 2.1 instead

**Comment by BeverlyBean** [comment]
do we still need this PR when axo done did everything

**Comment by gheskett** [comment]
The last commit that was made to lighting engine was early June, so it's months outdated. I'm not sure whether this PR should be reopened with something more up-to-date but I'm gonna leave it alone for now.

**Comment by BeverlyBean** [comment]
but like shouldnt we switch it from reonu's repo to the develop/2.1.0-lighting-engine branch

**Comment by gheskett** [comment]
I didn't realize that branch existed, I will close this PR then

**Pull request closed without merging**
