### PR TITLE
get rid of the unused CRAP!!!

### PR DESCRIPTION
**Pull request by PyrolluxJay**
i hate hacker sm64

### CODE REVIEW

**Comment by PyrolluxJay** [comment]
grrrr let me merge

**Review by arthurtilly — CHANGES_REQUESTED** [review]
this pr sucks BALLS! if ur gonna remove them then remove them properly smh

**Comment by PyrolluxJay** [comment]
im gonna kick you!!

**Comment by gheskett** [comment]
These are static inclusions so they probably aren't being compiled into the ROM anyway. Don't really see a point innmerging this guy.

**Pull request closed without merging**
