### PR TITLE
Allow quicksand ledge grabs

### PR DESCRIPTION
**Pull request by Arceveti**
Also adds missing LEDGE_GRABS_CHECK_SLOPE_ANGLE guard in check_ledge_grab

### CODE REVIEW

**Review by arthurtilly — CHANGES_REQUESTED** [review]
no

**Comment by axollyon** [comment]
> no

no this is a good thing, it lets you avoid the absolutely awful disgusting quicksand ledgegrab """"fix""""

**Comment by axollyon** [comment]
actually what if we just removed the fix, can we remove the fix altogether

**Comment by arthurtilly** [comment]
the “no” was in regards to making it a define lmao, not the fix

**Review by axollyon — APPROVED** [review]
yes

**Comment by arthurtilly** [comment]
looks fine now but should this really be on 2.1? might be better to add it to my master pr. also maybe worth removing the existing code for LEDGE_GRABS_CHECK_SLOPE_ANGLE since its unnecessary now

**Comment by arthurtilly** [comment]
fixed by #512

**Pull request closed without merging**
