### PR TITLE
Delete config_interaction.h

### LINKED ISSUE #435: Remove config_interactions.h file, move the one define it has somewhere else
it has one define

wtf

### PR DESCRIPTION
**Pull request by Reonu**
Fixes #435

### CODE REVIEW

**Review by Arceveti — APPROVED** [review]
lgtm

**Comment by arthurtilly** [comment]
based

**Comment by thecozies** [comment]
@Reonu conflicts it needs has resolved help aaaaaaaa

**Comment by Reonu** [comment]
@thecozies

**Review by thecozies — APPROVED** [review]

**Pull request merged**
