### PR TITLE
Remove sharp transitions

### PR DESCRIPTION
**Pull request by Lilaa3**
Completly missed this in the last pr. This time i tested WITH the define.

### CODE REVIEW

**Review by gheskett — CHANGES_REQUESTED** [review]
Still doesn't look right:
- Circle radius is way too large
- Texture outlines are leaking outside of the visible circle

Original:
image

Sharp Transition Textures:
image

**Comment by Lilaa3** [comment]
I like the idea but it really isn´t very vanilla and causes issues.
Might be worth revisiting but for now lets just get rid of it.

**Comment by Lilaa3** [comment]
Missing render mode, hold on

**Review by gheskett — APPROVED** [review]

**Review by thecozies — APPROVED** [review]
# its 2.1 time

**Pull request merged**
