### PR TITLE
Merge master/2.0.5 into 2.1.0

### PR DESCRIPTION
**Pull request by Arceveti**

### CODE REVIEW

**Review by thecozies — APPROVED** [review]

**Review by axollyon — APPROVED** [review]
didn't run into any issues having done this manually in my own repo 👍

**Review by gheskett — APPROVED** [review]
I assume merge conflicts have already been addressed and everything.

**Comment by Arceveti** [comment]
There are merge conflicts I can't resolve because master is a protected branch.

**Review by arthurtilly — CHANGES_REQUESTED** [review]
i don't think this is a good idea right now it will just cause all authors of current dev branches to be forced to resolve conflicts individually instead of only one person needing to resolve conflicts at the end of 2.1 development

**Comment by gheskett** [comment]
Ah right, maybe try opening a PR in another duplicate branch instead

**Review by arthurtilly — APPROVED** [review]
ok fine

**Comment by gheskett** [comment]
Not necessarily, if anything pushing conflicts out will potentially make them more difficult to fix later. Idk if these changes in particular will raise many new conflicts for most other in-progress branches currently.

**Comment by Arceveti** [comment]
Moved to #536

**Pull request closed without merging**
