### PR TITLE
Fix outdated semicolons

### PR DESCRIPTION
**Pull request by fuel-pcbox**
We use Greek question marks now.

### CODE REVIEW

**Comment by gheskett** [comment]
wh

**Comment by fuel-pcbox** [comment]
Message received. You do not like modern development practices!!! WAIT UNTIL THE BOSS HEARS ABOUT THIS!!

**Comment by Anonymous941** [comment]
What the heck???

**Comment by fuel-pcbox** [comment]
funi

**Comment by Anonymous941** [comment]
Uh... okay...

**Comment by TheEssem** [comment]
this filled up my github homepage thank you

image

**Comment by Anonymous941** [comment]
imho that's kind of GitHub's fault

**Pull request closed without merging**
