### PR TITLE
Wrap boulder room check under vanilla specific level checks

### PR DESCRIPTION
**Pull request by Reonu**
In vanilla boulders only spawn if mario is in a specific room. This is now wrapped under `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS`

### CODE REVIEW

**Comment by Reonu** [comment]
lol I pointed to master lmao!!!!

**Comment by thecozies** [comment]
maybe develop/2.1

**Comment by Reonu** [comment]
mayhaps

(fixed)

**Review by gheskett — APPROVED** [review]

**Review by arthurtilly — APPROVED** [review]
true!

**Pull request merged**
