### PR TITLE
Fixed broken Makefile

### PR DESCRIPTION
**Pull request by mpharoah**
Make HackerSM64 actually build

Makefile was relying on a variable it never sets, so it just calls `cat` with no arguments and hangs forever

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
Odd that something like this wasn't noticed sooner

**Comment by mpharoah** [comment]
Yeah, I don't know how it could possibly work for anybody even with local changes in their build directory.

Unless wsl2 does something phenomenally stupid that makes it not hang somehow, which is entirely possible

**Comment by mpharoah** [comment]
Ah, it probably works if the sounds are already build from a previous working branch so it just never hits that Makefile target

**Comment by gheskett** [comment]
I highly doubt it since I build from clean almost compulsively

**Pull request merged**
