### PR TITLE
Release/2.1.0

### PR DESCRIPTION
**Pull request by thecozies**

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
monkaS

**Comment by BeverlyBean** [comment]
https://images.seattletimes.com/wp-content/uploads/2021/07/food-squash-bf86a74c-de6d-11eb-9f54-7eee10b5fcd2.jpg?d=780x520

**Comment by BeverlyBean** [comment]
food-squash-bf86a74c-de6d-11eb-9f54-7eee10b5fcd2

**Review by Reonu — APPROVED** [review]
hiiii

**Pull request merged**
