### PR TITLE
added SKIP_OBJECTS_OUTSIDE_ROOM define

### LINKED ISSUE #413: Objects in different rooms should stop running their code
There should also be an object flag to add exceptions to this.

### PR DESCRIPTION
**Pull request by MrComit**
skips running object code when outside of the object's room

Fixes #413

### CODE REVIEW

**Review by Reonu — APPROVED** [review]
yoooo thank you

**Comment by Reonu** [comment]
WAIT YOU POINTED IT AT MASTER LMAO

**Comment by MrComit** [comment]
i explicitly asked you what the branch structure of this project was and i was never told what branch to point it at 😔

**Review by thecozies — CHANGES_REQUESTED** [review]
@MrComit this PR looks like it now has some changes that were outside of your actual changes. would you mind rebasing onto develop/2.1.0? if you look through `Files changed` you can see what i mean

**Comment by Reonu** [comment]
closing this since arthur's PR replaces it

**Pull request closed without merging**
