### PR TITLE
added make_patch and flips

### PR DESCRIPTION
**Pull request by thecozies**
needs some verification from @someone2639 for both cleanliness and if it works on the funny distro. it just builds flips from scratch!

### CODE REVIEW

**Review by gheskett — APPROVED** [review]
Just going to assume this works (I am out of the country until Memorial Day).

Although, what are the thoughts behind using this with `make release`?

**Review by someone2639 — APPROVED** [review]
works on my machine

**Comment by thecozies** [comment]
> Just going to assume this works (I am out of the country until Memorial Day).
> 
> Although, what are the thoughts behind using this with `make release`?

@gheskett yeah when we add make release we can call this target, still nice to have this separate just in case you need to create a debug patch

**Comment by someone2639** [comment]
if this were to be adapted to support a `make release`, it might be worth having the `patch` target only list a bps file (like how `all` only lists the rom) and have a rule that creates a bps from a z64 so that `release` can share the command

**Pull request merged**
