### PR TITLE
Added config option for previewable blue coins

### PR DESCRIPTION
**Pull request by gheskett**
Adds config option for the following feature:
 - When Mario is standing on an idle blue coin switch, blue coins associated with the switch will become visible.

Compatible with `BLUE_COIN_SWITCH_RETRY` config option.
___
Copied over from #143 to make collaborative adjustments easier

### CODE REVIEW

**Comment by gheskett** [comment]
I tried adding an option for coin flickering but I personally just don't think it looks good. I also tried doing it with opacity but I wasn't able to get it working for some reason. I think the opacity option would be best if it can be done in a non-conflicting manner, but otherwise I think opaque coins aesthetically superior to any rate of flickering.

**Review by Reonu — APPROVED** [review]
@gheskett what about dithering? in any case lgtm

**Comment by Reonu** [comment]
any reason not to merge this right now @thecozies @arthurtilly

**Comment by arthurtilly** [comment]
idk i dont like it much implementation isnt clean so i didnt review it

**Comment by gheskett** [comment]
I still think alpha or dithering would go a long way for this define personally, but again I'm not the best candidate for the job. Though like I said before, coin flicker is not a satisfactory solution.

**Comment by Mineqwerty** [comment]
Though I believe that having any blue coin preview would be good, if nobody ends up agreeing on the implementation we could always just push this back to a later version since its not really necessary for 2.1

**Review by thecozies — APPROVED** [review]
approved though we should add an issue to have this be dithered or something that isnt just them sitting there

**Comment by gheskett** [comment]
3.0 though

**Pull request merged**
